# Generated by Django 4.2.4 on 2023-08-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_identifier', models.FloatField()),
                ('salary', models.FloatField()),
                ('other_salary', models.FloatField()),
                ('total_salary', models.FloatField()),
                ('retirement', models.FloatField()),
                ('health_dental', models.FloatField()),
                ('other_benefits', models.FloatField()),
                ('total_benefits', models.FloatField()),
                ('total_compensation', models.FloatField()),
                ('created_dt', models.DateTimeField(auto_now=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
